icon_url: https://truecharts.org/img/hotlink-ok/chart-icons/bazarr.png
categories:
  - media
screenshots:
  - https://bazarr.tv/img/features/calendar.png
  - https://bazarr.tv/img/features/manualsearch.png
  - https://bazarr.tv/img/features/blocklist.png
tags:
  - series
