remote: origin
target-branch: master
helm-extra-args: --timeout 600s
# This is too verbose, contains the rendered k8s objects
# helm-extra-args: --timeout 600s --debug
chart-yaml-schema: .github/ct-install-config/chart_schema.yaml
debug: false
# Also test upgrade on each app/ci-values
upgrade: true
chart-dirs:
  - library/dev/charts
excluded-charts:
  - common-test
  - common
  # GH Runner does not have the required storage space
  - storj
